const dbConfig = require('../config/db.config');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.users = require('./user.model')(mongoose); //tabela de usuários
db.products = require('./product.model')(mongoose); //tabela de produtos
db.orders = require('./order.model')(mongoose); //tabela de pedidos
module.exports = db;